# Generated by Django 5.0.7 on 2024-07-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
    ]
