# Generated by Django 5.0.7 on 2024-07-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descrpition',
            new_name='description',
        ),
    ]
