# Generated by Django 5.0.7 on 2024-08-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('item', '0005_rename_descrpition_item_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='CartItem',
        ),
    ]
