# Generated by Django 5.0.7 on 2024-08-03 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_quotationinfo_quotationitem_delete_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='quotationinfo',
            name='username',
        ),
        migrations.AddField(
            model_name='quotationinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoted_items', to='cart.quotationinfo'),
        ),
    ]
