# Generated by Django 5.0.7 on 2024-08-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_quotationinfo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationinfo',
            name='email',
            field=models.TextField(default='example@example.com', max_length=80),
        ),
        migrations.AddField(
            model_name='quotationinfo',
            name='tax_code',
            field=models.TextField(default='12344321', max_length=50),
        ),
        migrations.AlterField(
            model_name='quotationinfo',
            name='user',
            field=models.TextField(max_length=50),
        ),
    ]
