# Generated by Django 5.0.7 on 2024-08-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_quotationinfo_email_quotationinfo_tax_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationinfo',
            name='email',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='quotationinfo',
            name='tax_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quotationinfo',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
