# Generated by Django 5.0.7 on 2024-08-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_quotationinfo_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='quotationinfo',
            name='username',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='quotationinfo',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
