# Generated by Django 5.0.7 on 2024-08-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_quotationitem_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
