# Generated by Django 5.0.7 on 2024-08-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_quotationitem_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationinfo',
            name='phonenum',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationinfo',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
